/******** IMG **********/
import {
  Fiat_500_1,
  Fiat_500_2,
  Fiat_500_3,
  Fiat_500_4,
  Fiat_500_5,
  Fiat_500_6,
  Fiat_500_7,
  Fiat_500_8,
  Fiat_500_9,
  Fiat_500_10,
  Kia_Sportage_1,
  Kia_Sportage_2,
  Kia_Sportage_3,
  Kia_Sportage_4,
  Kia_Sportage_5,
  Kia_Sportage_6,
  Nissan_Qashqai_1,
  Nissan_Qashqai_2,
  Nissan_Qashqai_3,
  Nissan_Qashqai_4,
  Nissan_Qashqai_5,
  Nissan_Leaf_1,
  Nissan_Leaf_2,
  Nissan_Leaf_3,
  Nissan_Leaf_4,
  Nissan_Leaf_5,
  Tesla_1,
  Tesla_2,
  Tesla_3,
  Tesla_4,
  Tesla_5,
  Tesla_6,
  Volkswagen_VII_1,
  Volkswagen_VII_2,
  Volkswagen_VII_3,
  Volkswagen_VII_4,
  Volkswagen_VII_5,
  Volkswagen_VII_6,
  Volkswagen_VI_1,
  Volkswagen_VI_2,
  Volkswagen_VI_3,
  Volkswagen_VI_4,
  Volkswagen_VI_5,
  Volkswagen_VI_6,
  Volkswagen_Electro_1,
  Volkswagen_Electro_2,
  Volkswagen_Electro_3,
  Volkswagen_Electro_4,
  Volkswagen_Electro_5,
  Ford_transit_1,
  Ford_transit_2,
  Ford_transit_3,
  Ford_transit_4,
  Ford_transit_5,
  Ford_transit_6,
  Ford_transit_7,
  Volkswagen_Kombi_1,
  Volkswagen_Kombi_2,
  Volkswagen_Kombi_3,
  Volkswagen_Kombi_4,
  Volkswagen_Kombi_5,
  Volkswagen_Kombi_6,
  Volkswagen_Kombi_7,
  Volkswagen_Kombi_8,
  Honda_Varadero_1,
  Honda_Varadero_2,
  Honda_Varadero_3,
  Honda_Varadero_4,
  Honda_Varadero_5,
  Horwin_electro_1,
  Horwin_electro_2,
  Horwin_electro_3,
  Horwin_electro_4,
  Kymco_Agility_1,
  Kymco_Agility_2,
  Kymco_Agility_3,
  Kymco_Agility_4,
  Kymco_Agility_5,
  Kymco_X_1,
  Kymco_X_2,
  Kymco_X_3,
  Kymco_X_4,
  Kymco_X_5,
  Kymco_X_6,
  Kymco_X_7,
  Kymco_X_8,
  Kymco_X_9,
  Luxxon_Emily_1,
  Luxxon_Emily_2,
  Luxxon_Emily_3,
  Luxxon_Emily_4,
  Luxxon_Emily_5,
  Piaggio_Electro_1,
  Piaggio_Electro_2,
  Piaggio_Electro_3,
  Piaggio_Electro_4,
  Piaggio_Electro_5,
  Piaggio_Electro_6,
  Yamaha_XJ6_1,
  Yamaha_XJ6_2,
  Yamaha_XJ6_3,
  Yamaha_XJ6_4,
  Yamaha_XJ6_5,
} from "../images/images.js";

export const VEHICLE_DATA = [
  {
    vehicle: "car",
    name: "Fiat 500 S Cabrio Sport",
    price: "15000",
    img: Fiat_500_1,
    imgs: [
      Fiat_500_1,
      Fiat_500_2,
      Fiat_500_3,
      Fiat_500_4,
      Fiat_500_5,
      Fiat_500_6,
      Fiat_500_7,
      Fiat_500_8,
      Fiat_500_9,
      Fiat_500_10,
    ],
    bag: "2",
    seats: "2",
    doors: "2/3",
    power: "90",
    transmission: "Manual",
    fuel: "Petrol",
    id: 1,
  },

  {
    vehicle: "car",
    name: "Kia Sportage ",
    price: "19800",
    img: Kia_Sportage_1,
    imgs: [
      Kia_Sportage_1,
      Kia_Sportage_2,
      Kia_Sportage_3,
      Kia_Sportage_4,
      Kia_Sportage_5,
      Kia_Sportage_6,
    ],
    bag: "4",
    seats: "5",
    doors: "4/5",
    power: "135",
    transmission: "Manual",
    fuel: "Petrol",
    id: 2,
  },

  {
    vehicle: "car",
    name: "Nissan Qashqai Acenta",
    price: "21100",
    img: Nissan_Qashqai_1,
    imgs: [
      Nissan_Qashqai_1,
      Nissan_Qashqai_2,
      Nissan_Qashqai_3,
      Nissan_Qashqai_4,
      Nissan_Qashqai_5,
    ],
    bag: "4",
    seats: "5",
    doors: "4/5",
    power: "117",
    transmission: "Automatic",
    fuel: "Petrol",
    id: 3,
  },

  {
    vehicle: "car",
    name: "Nissan Leaf",
    price: "29000",
    img: Nissan_Leaf_1,
    imgs: [
      Nissan_Leaf_1,
      Nissan_Leaf_2,
      Nissan_Leaf_3,
      Nissan_Leaf_4,
      Nissan_Leaf_5,
    ],
    bag: "3",
    seats: "4",
    doors: "4/5",
    power: "122",
    transmission: "Automatic",
    fuel: "Electric",
    id: 4,
  },

  {
    vehicle: "car",
    name: "Tesla Model S 85",
    price: "42000",
    img: Tesla_1,
    imgs: [Tesla_1, Tesla_2, Tesla_3, Tesla_4, Tesla_5, Tesla_6],
    bag: "4",
    seats: "5",
    doors: "4/5",
    power: "367",
    transmission: "Automatic",
    fuel: "Electric",
    id: 5,
  },

  {
    vehicle: "car",
    name: "Volkswagen Golf VII Variant",
    price: "25000",
    img: Volkswagen_VII_1,
    imgs: [
      Volkswagen_VII_1,
      Volkswagen_VII_2,
      Volkswagen_VII_3,
      Volkswagen_VII_4,
      Volkswagen_VII_5,
      Volkswagen_VII_6,
    ],
    bag: "5",
    seats: "5",
    doors: "4/5",
    power: "116",
    transmission: "Manual",
    fuel: "Diesel",
    id: 6,
  },

  {
    vehicle: "car",
    name: "Volkswagen Golf VI",
    price: "21000",
    img: Volkswagen_VI_1,
    imgs: [
      Volkswagen_VI_1,
      Volkswagen_VI_2,
      Volkswagen_VI_3,
      Volkswagen_VI_4,
      Volkswagen_VI_5,
      Volkswagen_VI_6,
    ],
    bag: "2",
    seats: "4",
    doors: "2/3",
    power: "110",
    transmission: "Manual",
    fuel: "Petrol",
    id: 7,
  },

  {
    vehicle: "car",
    name: "Volkswagen E-up",
    price: "24000",
    img: Volkswagen_Electro_1,
    imgs: [
      Volkswagen_Electro_1,
      Volkswagen_Electro_2,
      Volkswagen_Electro_3,
      Volkswagen_Electro_4,
      Volkswagen_Electro_5,
    ],
    bag: "2",
    seats: "4",
    doors: "4/5",
    power: "82",
    transmission: "Automatic",
    fuel: "Electric",
    id: 8,
  },

  {
    vehicle: "car",
    name: "Ford Transit Kombi FT 300 L ",
    price: "33000",
    img: Ford_transit_1,
    imgs: [
      Ford_transit_1,
      Ford_transit_2,
      Ford_transit_3,
      Ford_transit_4,
      Ford_transit_5,
      Ford_transit_6,
      Ford_transit_7,
    ],
    bag: "9",
    seats: "9",
    doors: "3/4",
    power: "101",
    transmission: "Manual",
    fuel: "Diesel",
    id: 9,
  },

  {
    vehicle: "car",
    name: "Volkswagen T6",
    price: "34990",
    img: Volkswagen_Kombi_1,
    imgs: [
      Volkswagen_Kombi_1,
      Volkswagen_Kombi_2,
      Volkswagen_Kombi_3,
      Volkswagen_Kombi_4,
      Volkswagen_Kombi_5,
      Volkswagen_Kombi_6,
      Volkswagen_Kombi_7,
      Volkswagen_Kombi_8,
    ],
    bag: "16",
    seats: "3",
    doors: "3/4",
    power: "102",
    transmission: "Manual",
    fuel: "Disele",
    id: 10,
  },

  /**************  Motro ***************************/
  {
    vehicle: "motor",
    name: "Honda Varadero ",
    price: "16000",
    img: Honda_Varadero_1,
    imgs: [
      Honda_Varadero_1,
      Honda_Varadero_2,
      Honda_Varadero_3,
      Honda_Varadero_4,
      Honda_Varadero_5,
    ],
    bag: "3",
    seats: "2",
    power: "94",
    transmission: "Manual",
    fuel: "Petrol",
    id: 11,
  },
  {
    vehicle: "motor",
    name: "Horwin ",
    price: "15000",
    img: Horwin_electro_1,
    imgs: [
      Horwin_electro_1,
      Horwin_electro_2,
      Horwin_electro_3,
      Horwin_electro_4,
    ],
    seats: "2",
    power: "8",
    transmission: "Automatic",
    fuel: "Electric",
    id: 12,
  },

  {
    vehicle: "motor",
    name: "Kymco Agility",
    price: "9900",
    img: Kymco_Agility_1,
    imgs: [
      Kymco_Agility_1,
      Kymco_Agility_2,
      Kymco_Agility_3,
      Kymco_Agility_4,
      Kymco_Agility_5,
    ],
    seats: "2",
    power: "3",
    transmission: "Automatic",
    fuel: "Petrol",
    id: 13,
  },

  {
    vehicle: "motor",
    name: "Kymco X-Town",
    price: "11990",
    img: Kymco_X_1,
    imgs: [
      Kymco_X_1,
      Kymco_X_2,
      Kymco_X_3,
      Kymco_X_4,
      Kymco_X_5,
      Kymco_X_6,
      Kymco_X_7,
      Kymco_X_8,
      Kymco_X_9,
    ],
    seats: "2",
    power: "24",
    transmission: "Automatic",
    fuel: "Petrol",
    id: 14,
  },

  {
    vehicle: "motor",
    name: "Luxxon Emily",
    price: "8000",
    img: Luxxon_Emily_1,
    imgs: [
      Luxxon_Emily_1,
      Luxxon_Emily_2,
      Luxxon_Emily_3,
      Luxxon_Emily_4,
      Luxxon_Emily_5,
    ],
    seats: "1",
    power: "4",
    transmission: "Automatic",
    fuel: "Petrol",
    id: 15,
  },
  {
    vehicle: "motor",
    name: "Piaggio 1 ",
    price: "13000",
    img: Piaggio_Electro_1,
    imgs: [
      Piaggio_Electro_1,
      Piaggio_Electro_2,
      Piaggio_Electro_3,
      Piaggio_Electro_4,
      Piaggio_Electro_5,
      Piaggio_Electro_6,
    ],
    seats: "1",
    power: "4",
    transmission: "Automatic",
    fuel: "Electric",
    id: 16,
  },

  {
    vehicle: "motor",
    name: "Yamaha XJ6",
    price: "14000",
    img: Yamaha_XJ6_1,
    imgs: [
      Yamaha_XJ6_1,
      Yamaha_XJ6_2,
      Yamaha_XJ6_3,
      Yamaha_XJ6_4,
      Yamaha_XJ6_5,
    ],
    seats: "2",
    power: "48",
    transmission: "Manual",
    fuel: "Petrol",
    id: 17,
  },
];
